//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELFCHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterOfMassDisplacmnet
    {
        public int ID { get; set; }
        public string Story { get; set; }
        public string Diaphragm { get; set; }
        public string Output_Case { get; set; }
        public string Case_Type { get; set; }
        public string Step_Type { get; set; }
        public Nullable<double> UX { get; set; }
        public Nullable<double> UY { get; set; }
        public Nullable<double> RZ { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public Nullable<double> Z { get; set; }
    }
}
