//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELFCHK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBELFEntities : DbContext
    {
        public DBELFEntities()
            : base("name=DBELFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBEccentricity> TBEccentricities { get; set; }
        public virtual DbSet<Eccentricity> Eccentricities { get; set; }
        public virtual DbSet<GridDefinitionsGridLinesData> GridDefinitionsGridLinesDatas { get; set; }
        public virtual DbSet<CenterOfMassDisplacmnet> CenterOfMassDisplacmnets { get; set; }
        public virtual DbSet<StoryDefiniton> StoryDefinitons { get; set; }
        public virtual DbSet<StoryForce> StoryForces { get; set; }
        public virtual DbSet<TBPDelta> TBPDeltas { get; set; }
    }
}
