//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELFCHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eccentricity
    {
        public int ID { get; set; }
        public Nullable<double> ex { get; set; }
        public Nullable<double> ey { get; set; }
        public Nullable<double> Dx { get; set; }
        public Nullable<double> Dy { get; set; }
        public Nullable<double> exResult { get; set; }
        public string exState { get; set; }
        public Nullable<double> eyResult { get; set; }
        public string eyState { get; set; }
        public string Story { get; set; }
    }
}
