//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELFCHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridDefinitionsGridLinesData
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Grid_Line_Type { get; set; }
        public string IDT { get; set; }
        public Nullable<double> Ordinate { get; set; }
        public string Bubble_Location { get; set; }
        public string Visible { get; set; }
    }
}
