//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELFCHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryDefiniton
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Height { get; set; }
        public string Master_Story { get; set; }
        public string Similar_To { get; set; }
        public string Splice_Story { get; set; }
        public string Color { get; set; }
        public string Guid { get; set; }
    }
}
