//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELFCHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryForce
    {
        public int ID { get; set; }
        public string Story { get; set; }
        public string output_Case { get; set; }
        public string Case_Type { get; set; }
        public string Step_Type { get; set; }
        public string Location { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> VX { get; set; }
        public Nullable<double> VY { get; set; }
        public Nullable<double> T { get; set; }
        public Nullable<double> MX { get; set; }
        public Nullable<double> MY { get; set; }
    }
}
