//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELFCHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBEccentricity
    {
        public int ID { get; set; }
        public string Story { get; set; }
        public string Diaphragm { get; set; }
        public Nullable<double> MassX { get; set; }
        public Nullable<double> MassY { get; set; }
        public Nullable<double> XCM { get; set; }
        public Nullable<double> YCM { get; set; }
        public Nullable<double> CummX { get; set; }
        public Nullable<double> CummY { get; set; }
        public Nullable<double> XCCM { get; set; }
        public Nullable<double> YCCM { get; set; }
        public Nullable<double> XCR { get; set; }
        public Nullable<double> YCR { get; set; }
        public Nullable<double> Dx { get; set; }
        public Nullable<double> Dy { get; set; }
    }
}
