//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELFCHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPDelta
    {
        public int ID { get; set; }
        public string Story { get; set; }
        public Nullable<double> H { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> V { get; set; }
        public Nullable<double> U { get; set; }
        public Nullable<double> Delta { get; set; }
        public Nullable<double> Theta { get; set; }
        public Nullable<double> Theta_Max { get; set; }
        public string State { get; set; }
    }
}
